Started documenting behaviors
MicrosoftDocs/xamarin-communitytoolkit pull request #36
Opened 2020-12-07 13:49 UTC by sthewissen

## Fixes #7 

## What changes to the docs does this PR provide?
Documents all the current behaviors in the XCT.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [X] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/toc.yml).
- [X] Ran against a spell and grammar checker.
- [X] Contains **NO** breaking changes.

## Other information

2020-12-07 13:50 UTC, davidbritch commented
Docs Build status updates of commit _[49ae5f4](https://github.com/sthewissen/xamarin-communitytoolkit/commits/49ae5f4db6907de42aa463a923492489cb7cbfd1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012071349136294-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8Q5exnDdwFkdkpn77xkf1r5W0LuHp%2FTMPAxmS0%2BXu7o%3D&st=2020-12-07T13%3A45%3A14Z&se=2021-01-07T13%3A50%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 14:34 UTC, davidbritch commented
Docs Build status updates of commit _[9638d44](https://github.com/sthewissen/xamarin-communitytoolkit/commits/9638d44098b0fee36ab612df179a10b4eb9ca57e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012071433308486-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VXo1jcDvIvAxOqVPviLxiCKNmBOEu8wyAMn9foa%2BQbY%3D&st=2020-12-07T14%3A29%3A16Z&se=2021-01-07T14%3A34%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 15:09 UTC, davidbritch commented
@sthewissen I'll have created a merge nightmare for you, so it might be wise to rebase now. Sorry!

2020-12-07 15:09 UTC, davidbritch commented
Docs Build status updates of commit _[0416f09](https://github.com/sthewissen/xamarin-communitytoolkit/commits/0416f09df29a31234769afaa5d1698559839e53d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3f2f93a1)

<a id="3f2f93a1"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012071509332806-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MhfA3cOIdDWelntIlwmooIPQC5MadoCuCOobn%2FNqR4c%3D&st=2020-12-07T15%3A04%3A46Z&se=2021-01-07T15%3A09%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 20:35 UTC, davidbritch commented
Docs Build status updates of commit _[dc896e7](https://github.com/sthewissen/xamarin-communitytoolkit/commits/dc896e7ce7eff50e4c914848cd2ddbff194cff7d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8a76469f)

<a id="8a76469f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012072035005455-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L9FOPM%2FoTWYqWkAC%2F2SR3OYkSzYEpGbJn7F1g%2BACd5g%3D&st=2020-12-07T20%3A30%3A15Z&se=2021-01-07T20%3A35%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 20:41 UTC, davidbritch commented
Docs Build status updates of commit _[0a6ed1a](https://github.com/sthewissen/xamarin-communitytoolkit/commits/0a6ed1af4bd98c74b4695cebb4727585ad52de53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012072040501732-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YNCRmePc%2FAFVoiNR%2BkAzzDM9E1rZdz0UStymNif1WA0%3D&st=2020-12-07T20%3A36%3A43Z&se=2021-01-07T20%3A41%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 20:42 UTC, sthewissen commented
@davidbritch Should be good again!

2020-12-07 20:43 UTC, davidbritch commented
Docs Build status updates of commit _[06eb3e1](https://github.com/sthewissen/xamarin-communitytoolkit/commits/06eb3e1e65d803ee536f3f2b33d927c2446c6e4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012072042277919-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WaE12nqcANwbno%2F9H%2BVci%2B9LBkdAJMRZvS46gxyvUPk%3D&st=2020-12-07T20%3A38%3A04Z&se=2021-01-07T20%3A43%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 14:42 UTC, davidbritch commented
Docs Build status updates of commit _[108a049](https://github.com/sthewissen/xamarin-communitytoolkit/commits/108a049c57ede4a8fbbb3155cedeb14ad6213843)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-08 14:43 UTC, davidbritch commented
Docs Build status updates of commit _[108a049](https://github.com/sthewissen/xamarin-communitytoolkit/commits/108a049c57ede4a8fbbb3155cedeb14ad6213843)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012081442523847-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iUknNOyMhmN2Lw3UEuhX9Ku%2Bc9j%2FYxVs02XqD591Ohw%3D&st=2020-12-08T14%3A38%3A31Z&se=2021-01-08T14%3A43%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 15:29 UTC, davidbritch commented
Docs Build status updates of commit _[ddf26ff](https://github.com/sthewissen/xamarin-communitytoolkit/commits/ddf26ff20f4218d1788061af2ac2f14a5b78b54c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012081528271618-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uOMy4qlQoZdtFHi1gzcHSHcqIopSRNmeMfourtJm%2FIU%3D&st=2020-12-08T15%3A24%3A11Z&se=2021-01-08T15%3A29%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 21:34 UTC, davidbritch commented
Docs Build status updates of commit _[639db8a](https://github.com/sthewissen/xamarin-communitytoolkit/commits/639db8a8eadd58cfb869d308e80618a6f80d76da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012082134126488-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FYhYYRTQekk0Q6JzQhFlohht3P0kTWwBU7H29TZh4oA%3D&st=2020-12-08T21%3A29%3A56Z&se=2021-01-08T21%3A34%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 10:23 UTC, davidbritch commented
Docs Build status updates of commit _[12161a3](https://github.com/sthewissen/xamarin-communitytoolkit/commits/12161a385df2d78823b6c4ecda72bb38afc2440e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091022574982-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=65QH9JxJuh%2FEBfyfB8wJu0WdSZV6iAH39dt%2BDnasfAg%3D&st=2020-12-09T10%3A18%3A35Z&se=2021-01-09T10%3A23%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 10:57 UTC, davidbritch commented
Docs Build status updates of commit _[49b3ce9](https://github.com/sthewissen/xamarin-communitytoolkit/commits/49b3ce9b0c2e89217feeac081b1d03d35d3c9617)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091056354543-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nanh4RvUK%2FVWyg0fDanaCqtjuv1khmvnDE8ZOADp91I%3D&st=2020-12-09T10%3A52%3A14Z&se=2021-01-09T10%3A57%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 10:59 UTC, davidbritch commented
Docs Build status updates of commit _[51f1720](https://github.com/sthewissen/xamarin-communitytoolkit/commits/51f17204b32a4a2f8ca72c0c01b90eebd7df2444)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091058261124-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=plHYDjYkOPemoxrghkpshU1Gc5Z%2FZFocQCdVdWe6AMs%3D&st=2020-12-09T10%3A54%3A10Z&se=2021-01-09T10%3A59%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 11:00 UTC, davidbritch commented
Docs Build status updates of commit _[5cb51eb](https://github.com/sthewissen/xamarin-communitytoolkit/commits/5cb51ebcfae0fdc340842293ef7626b1e612c591)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091100129513-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CVT3INO5J8Ql7gKVZfReT47iTWNVHTwp%2FY4M37Sqo3U%3D&st=2020-12-09T10%3A55%3A49Z&se=2021-01-09T11%3A00%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 11:02 UTC, davidbritch commented
Docs Build status updates of commit _[89dc1d6](https://github.com/sthewissen/xamarin-communitytoolkit/commits/89dc1d623e4af32b259468d52c23bdd5a93e01f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091101371353-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dDoG4tOlHX8YSQsE%2F%2FnmUkXbfyORtdcTtE%2BivjhljdM%3D&st=2020-12-09T10%3A57%3A24Z&se=2021-01-09T11%3A02%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 11:03 UTC, davidbritch commented
Docs Build status updates of commit _[157f58f](https://github.com/sthewissen/xamarin-communitytoolkit/commits/157f58f636f8a089956ae5c264cffbbe397a2556)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091102551353-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gx588m52FWktiPWwBfhSJLQneuaQquUwc27GvBeY%2BlE%3D&st=2020-12-09T10%3A58%3A40Z&se=2021-01-09T11%3A03%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 11:07 UTC, davidbritch commented
Docs Build status updates of commit _[bca6c3e](https://github.com/sthewissen/xamarin-communitytoolkit/commits/bca6c3e7cbc70d940b95bac3d14379e611631cad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091106348190-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uVnUdip0OUz2SlgUzywFb%2FfLo7jA636Mv0sLLPTA7X4%3D&st=2020-12-09T11%3A02%3A21Z&se=2021-01-09T11%3A07%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 11:08 UTC, davidbritch commented
Docs Build status updates of commit _[dbc5f4e](https://github.com/sthewissen/xamarin-communitytoolkit/commits/dbc5f4ebc9a513b26bcb1df47d4d7756a6047394)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091107485642-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RlpJY2lNwhIb2P5a7FWlqiGBxlSWL1hfub7qucYgezg%3D&st=2020-12-09T11%3A03%3A56Z&se=2021-01-09T11%3A08%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 11:10 UTC, davidbritch commented
Docs Build status updates of commit _[c29b3c8](https://github.com/sthewissen/xamarin-communitytoolkit/commits/c29b3c8b6ad22b7ca7ae8a3282f11596bce48a39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091109165656-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U6p1LWBBs1hlYnNew3jSF3c63tN5PHn%2FKULPJUyjzcY%3D&st=2020-12-09T11%3A05%3A03Z&se=2021-01-09T11%3A10%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 11:11 UTC, davidbritch commented
Docs Build status updates of commit _[2f347ae](https://github.com/sthewissen/xamarin-communitytoolkit/commits/2f347ae36a96ab3adee142522c13cce32ff3c03d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091110549653-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6hWZfC%2FEjIixd59VcBiYWeUEPWGHYnkh5QH5mMfyluE%3D&st=2020-12-09T11%3A06%3A39Z&se=2021-01-09T11%3A11%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 11:12 UTC, davidbritch commented
Docs Build status updates of commit _[37616ce](https://github.com/sthewissen/xamarin-communitytoolkit/commits/37616ce300e62bc52ea0b6049ffab660827183d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091112064611-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=45bOwH9QxLXekFyoavMvYkNwnR0cdl2u5EkXUdke5gU%3D&st=2020-12-09T11%3A07%3A52Z&se=2021-01-09T11%3A12%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 11:13 UTC, davidbritch commented
Docs Build status updates of commit _[1e01666](https://github.com/sthewissen/xamarin-communitytoolkit/commits/1e01666b3c71ee3a203ec6f5d7eb7110f3ae7006)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091112540180-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Jx0VNplqYkXJ5e0k2CdckhQL0OsMEPD6yalizHpD%2Ffk%3D&st=2020-12-09T11%3A08%3A39Z&se=2021-01-09T11%3A13%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 11:13 UTC, davidbritch requested changes
Thanks @sthewissen 

Just one update required: the properties table in the ValidationBehavior doc needs the description column populating.

2020-12-09 12:23 UTC, davidbritch commented
Docs Build status updates of commit _[c51ee6a](https://github.com/sthewissen/xamarin-communitytoolkit/commits/c51ee6a04b96ba15d81297024dabf5e9e4607d9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091223198653-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mTbKMLmyeYFjc3hLSmNwumR659R9aFwIxnHOL%2F2ulV8%3D&st=2020-12-09T12%3A18%3A58Z&se=2021-01-09T12%3A23%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 12:42 UTC, davidbritch approved these changes
Thanks @sthewissen

2020-12-09 12:43 UTC, davidbritch commented
Docs Build status updates of commit _[6c462a0](https://github.com/sthewissen/xamarin-communitytoolkit/commits/6c462a0f17628de535a33f9c2300e37de0aad72b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/animationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/animationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/animationbehavior?branch=pr-en-us-36) |
[docs/behaviors/charactersvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/charactersvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/charactersvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-36) |
[docs/behaviors/impliedordergridbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/impliedordergridbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/impliedordergridbehavior?branch=pr-en-us-36) |
[docs/behaviors/maskedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maskedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maskedbehavior?branch=pr-en-us-36) |
[docs/behaviors/maxlengthreachedbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/maxlengthreachedbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/maxlengthreachedbehavior?branch=pr-en-us-36) |
[docs/behaviors/multivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/multivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/multivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/requiredstringvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/requiredstringvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/requiredstringvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/urivalidationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/urivalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/urivalidationbehavior?branch=pr-en-us-36) |
[docs/behaviors/userstoppedtypingbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/userstoppedtypingbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/userstoppedtypingbehavior?branch=pr-en-us-36) |
[docs/behaviors/validationbehavior.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/behaviors/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012091242410879-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FPJz274guaKcp2KInHF0HLr%2FvphbYoZcp1Sxmbyp2TE%3D&st=2020-12-09T12%3A38%3A19Z&se=2021-01-09T12%3A43%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 09:11 UTC, merged