Initial Setup of pages for each type of toolkit item
MicrosoftDocs/xamarin-communitytoolkit pull request #4
Opened 2020-07-09 20:02 UTC by AlexHedley

## What changes to the docs does this PR provide?

Initial setup of the docs site.

Copied/updated some of the supplementary pages from Essentials

- get-started
- troubleshooting

Added the shells for each of the folders in the [XamarinCommunityToolkit](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit)

- Behaviors
- Converters
- Effects
- Extensions
- Interfaces
- Views

Updated the index page to link to these.

Although there isn't much content on this intial PR, it's more of a setup to help others get started quicker with the layout ready and easier to find where to start adding content.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/toc.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

2020-07-09 20:03 UTC, cmcclister commented
Docs Build status updates of commit _[d160c18](https://github.com/AlexHedley/xamarin-communitytoolkit/commits/d160c188b8bfb0b1adcd63a4d9a96bf8639cf1f2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/get-started.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/get-started.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-4) | [Details](#user-content-f5f9d1df-94d98f03)
[.gitignore](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/.gitignore) | :white_check_mark:Succeeded | |
[docs/TOC.yml](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-4) |
[docs/behaviors.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/behaviors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-4) |
[docs/converters.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/converters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/converters?branch=pr-en-us-4) |
[docs/effects.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/effects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects?branch=pr-en-us-4) |
[docs/extensions.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/extensions?branch=pr-en-us-4) |
[docs/helpers.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/helpers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/helpers?branch=pr-en-us-4) |
[docs/index.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-4) |
[docs/troubleshooting.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/troubleshooting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/troubleshooting?branch=pr-en-us-4) |
[docs/views.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/views.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views?branch=pr-en-us-4) |

<a id="f5f9d1df-94d98f03"></a>
### [docs/get-started.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/get-started.md)
 - **Line 15, Column 87**: **[Warning-file-not-found]** `````Invalid file link: '~/get-started/installation/index.md'.`````
 - **Line 61, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-gb/xamarin/get-started/' contains locale code 'en-gb'. For localizability, remove 'en-gb' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202007092002365154-4%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GcPjuEJrp6hPGujFqUQe5%2FU7TQoykoh5ZgQ5L1exTO8%3D&st=2020-07-09T19%3A58%3A04Z&se=2020-08-09T20%3A03%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-07-10 06:56 UTC, cmcclister commented
Docs Build status updates of commit _[61d304e](https://github.com/AlexHedley/xamarin-communitytoolkit/commits/61d304e3f399a9ec8987263f40ec98664b8c59fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.gitignore](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/.gitignore) | :white_check_mark:Succeeded | |
[docs/TOC.yml](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-4) |
[docs/behaviors.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/behaviors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-4) |
[docs/converters.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/converters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/converters?branch=pr-en-us-4) |
[docs/effects.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/effects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects?branch=pr-en-us-4) |
[docs/extensions.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/extensions?branch=pr-en-us-4) |
[docs/get-started.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-4) |
[docs/helpers.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/helpers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/helpers?branch=pr-en-us-4) |
[docs/index.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-4) |
[docs/troubleshooting.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/troubleshooting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/troubleshooting?branch=pr-en-us-4) |
[docs/views.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/views.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views?branch=pr-en-us-4) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C10%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202007100655398493-4%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iHVj0LmhcmawJOnfmOV0hJ0ckdnz1DGmf%2FckFk%2Bgft4%3D&st=2020-07-10T06%3A51%3A13Z&se=2020-08-10T06%3A56%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-07-10 09:09 UTC, davidbritch requested changes
Hi @AlexHedley 

Thanks for the PR. Great work. There's just a few minor updates required to ensure that Microsoft standards are followed. Thanks again!

2020-07-10 09:09 UTC, davidbritch commented on docs/get-started.md
> +# Get Started with Xamarin.CommunityToolkit
The Microsoft standard is to use sentence case for all titles and headings. So this will become "Get started with Xamarin.CommunityToolkit". See https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/contributing-guidelines/template.md#headings

I know there's loads of Microsoft docs that don't follow the standard, but we might as well get it right in a new docset :)

2020-07-10 09:09 UTC, davidbritch commented on docs/get-started.md
> +Xamarin.CommunityToolkit is available as a NuGet package and is included in every new project in Visual Studio. It can also be added to any existing using Visual Studio with the follow steps.
any existing what?

2020-07-10 09:09 UTC, davidbritch commented on docs/get-started.md
> +Xamarin.CommunityToolkit is available as a NuGet package and is included in every new project in Visual Studio. It can also be added to any existing using Visual Studio with the follow steps.
The Microsoft standard is to end the sentence before a list with a colon.

2020-07-10 09:09 UTC, davidbritch commented on docs/get-started.md
> +1. Download and install [Visual Studio](https://visualstudio.microsoft.com/) with the [Visual Studio tools for Xamarin](https://docs.microsoft.com/xamarin/get-started/installation/).
You should use a site-relative link here (tried to find a reference for this that's open to the outside world, and I can't). So:

https://docs.microsoft.com/xamarin/get-started/installation/

Will become:

/xamarin/get-started/installation/

Basically, links to other docs on docs.microsoft.com should never have https://docs.microsoft.com/ in them.

From an internal page:

Don't append the file extension .md on a link to an article in another repo or docset.

Site-relative links aren't validated at build time like file-relative links. If you have a typo in your link, no warning is generated. Site-relative links are also not click-navigable on the staging server review.docs.microsoft.com. To verify that the link works, replace the branch name in the link's generated URL with master.

2020-07-10 09:09 UTC, davidbritch commented on docs/get-started.md
> +We recommend developers new to Xamarin visit [getting started with Xamarin development](https://docs.microsoft.com/xamarin/get-started/).
Update the link.

2020-07-10 09:09 UTC, davidbritch commented on docs/get-started.md
> +## Other Resources
Use sentence casing.

2020-07-10 09:09 UTC, davidbritch commented on docs/index.md
> +## [Get Started with Xamarin.CommunityToolkit](get-started.md)
Use sentence casing.

2020-07-10 09:09 UTC, davidbritch commented on docs/index.md
> +## Feature Guides
Use sentence casing.

2020-07-10 09:29 UTC, AlexHedley commented
@davidbritch thanks for the great feedback, great things to know, as you say best to start off a new repo with all the best practices, I'll work on these a little later and ping when I'm done :)

2020-07-10 10:21 UTC, cmcclister commented
Docs Build status updates of commit _[f2f07d2](https://github.com/AlexHedley/xamarin-communitytoolkit/commits/f2f07d2dada14668e0fa6ba69f8eb173bac8d5d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.gitignore](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/.gitignore) | :white_check_mark:Succeeded | |
[docs/TOC.yml](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-4) |
[docs/behaviors.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/behaviors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-4) |
[docs/converters.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/converters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/converters?branch=pr-en-us-4) |
[docs/effects.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/effects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects?branch=pr-en-us-4) |
[docs/extensions.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/extensions?branch=pr-en-us-4) |
[docs/get-started.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-4) |
[docs/helpers.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/helpers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/helpers?branch=pr-en-us-4) |
[docs/index.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-4) |
[docs/troubleshooting.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/troubleshooting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/troubleshooting?branch=pr-en-us-4) |
[docs/views.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/views.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views?branch=pr-en-us-4) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C10%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202007101021006453-4%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Tt9TrRz%2F6zbwiuTRljiswmEvgLFiSGhiJfLzE1K2yn8%3D&st=2020-07-10T10%3A16%3A39Z&se=2020-08-10T10%3A21%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-07-10 10:23 UTC, cmcclister commented
Docs Build status updates of commit _[a6326b9](https://github.com/AlexHedley/xamarin-communitytoolkit/commits/a6326b96feec286d11d375d6aa4ff28b27e1bdfe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.gitignore](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/.gitignore) | :white_check_mark:Succeeded | |
[docs/TOC.yml](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-4) |
[docs/behaviors.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/behaviors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-4) |
[docs/converters.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/converters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/converters?branch=pr-en-us-4) |
[docs/effects.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/effects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects?branch=pr-en-us-4) |
[docs/extensions.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/extensions?branch=pr-en-us-4) |
[docs/get-started.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-4) |
[docs/helpers.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/helpers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/helpers?branch=pr-en-us-4) |
[docs/index.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-4) |
[docs/troubleshooting.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/troubleshooting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/troubleshooting?branch=pr-en-us-4) |
[docs/views.md](https://github.com/AlexHedley/xamarin-communitytoolkit/blob/setup/docs/views.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views?branch=pr-en-us-4) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C10%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202007101022564471-4%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SWgt3pwq1KsnXDiqQgrAGwmIL3qp5cO%2BkbdKgn1m6BA%3D&st=2020-07-10T10%3A18%3A37Z&se=2020-08-10T10%3A23%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-07-10 10:29 UTC, davidbritch approved these changes

2020-07-10 10:30 UTC, merged